// Mobile command chip buttons - tap to execute terminal commands
export const CHIPS = [
  "help",
  "ls",
  "whoami",
  "cat skills.txt",
  "cat contact.txt",
  "git log",
  "spotify --now-playing",
  "timeline",
  "work",
  "cat work.txt",
  "projects",
  "matrix",
  "replay",
  "sudo",
  "exit 8",
  "exit 8 fast",
  "split-fiction",
  "split-fiction 2",
  "tenet",
  "pokeball",
  "clear",
];
